version: '3'
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    env_file:
      - ./.env
    depends_on:
      - redis
    networks:
      - redisSocket
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - redisSocket

volumes:
  redis_data:

networks:
  redisSocket:
